### PR TITLE
Update NYCSubwayIcons.css

### PR DESCRIPTION
**Pull request by lucas-pelton**
Force a better circle shape, independent of font used

### CODE REVIEW

**Comment by chrisdl** [comment]
Hey, thanks for contributing this! The actual subway icons are written in the .sass file, so if you know how to use sass I would prefer if you updated that. If you don't I can absolutely port your fixes to the .sass file for you. I'll have a look at this pull sometime tomorrow. Thanks for committing!

**Comment by lucas-pelton** [comment]
I'm horrible at GitHub.  Sorry about the multiple commits in this pull request.  Also, it turned out that what I was trying to do was to reliable force a circle and enforce some padding around the text.  I'm new to sass, so excuse if the new rules are in the wrong place

**Comment by lucas-pelton** [comment]
image

**Comment by chrisdl** [comment]
No apologies needed! We all start somewhere =). However you are adding things which are specific to the text's location in the circle and your sass won't compile because you left the semicolons in. So I can't merge this. However it has made me aware of the fact that there should probably be more in the readme about actually implementing these icons. The code we have here is, by design, agnostic of sizes for the font and circle. This is because different people may want different sizes.

So the way to implement it is like so:

```
<element class="subway-icon subway-circle-1">
    <element class="subway-text">1</element>
</element>
```

This way you can set the circles size and font size to whatever you want in your code.

```
.subway-icon
    height: 20px
    width: 20px

.subway-text
    font-size: 14px
```

Does that make sense to you? What this library provides is the building blocks for creating a circle, with mta colors that has a perfectly centered helvetica font inside the circle across all devices which is white for all lines except the NQR where it is black. Sizing is left up to whomever implements it. If you want to contribute sass code, please install and run sass on the .sass file to create the .css file. You've made me aware that I should probably give some sort of contributing guide, so i'll add that as an issue to be added to the readme. 

Let me know if you need any more help implementing the library. expect some updates shortly addressing some of your concerns.

**Pull request closed without merging**
